name: AcuteCheck
version: ${project.version}
main: com.github.phillip.h.acutecheck.AcuteCheck
api-version: 1.13
authors: ["dizigma"]
description: In-game plugin test automation
commands:
  acutecheck:
    description: AcuteCheck parent command
    usage: /<command> [run]
    aliases: [ac]
permissions:
  acutecheck.*:
    description: All AcuteCheck permissions
    default: op
  acutecheck.run:
    description: Run AcuteCheck tests
    default: op
  acutecheck.help:
    description: See AcuteCheck help
    default: op
  acutecheck.list:
    description: List AcuteCheck tests
    default: op
  acutecheck.input:
    description: Run AcuteCheck input commands (/ac yes, etc)
    default: true
